-- MySQL Script generated by MySQL Workbench
-- Wed Aug  9 23:02:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Member` (
  `MEMBER_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `CITY` VARCHAR(45) NULL,
  `STREET` VARCHAR(45) BINARY NULL,
  `ZIPCODE` VARCHAR(45) NULL,
  PRIMARY KEY (`MEMBER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Delivery` (
  `DELIVERY_ID` INT NOT NULL,
  `CITY` VARCHAR(45) NULL,
  `STREET` VARCHAR(45) NULL,
  `ZIPCODE` VARCHAR(45) NULL,
  PRIMARY KEY (`DELIVERY_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `ORDER_ID` INT NOT NULL,
  `ORDER_DATE` DATETIME NULL,
  `MEMBER_ID` INT NULL,
  `DELIVERY_ID` INT NULL,
  PRIMARY KEY (`ORDER_ID`),
  INDEX `DELIVERY_ID_idx` (`DELIVERY_ID` ASC) VISIBLE,
  INDEX `MEMBER_ID_idx` (`MEMBER_ID` ASC) VISIBLE,
  CONSTRAINT `MEMBER_ID`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `mydb`.`Member` (`MEMBER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DELIVERY_ID`
    FOREIGN KEY (`DELIVERY_ID`)
    REFERENCES `mydb`.`Delivery` (`DELIVERY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ITEM` (
  `ITEM_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `PRICE` INT NULL,
  `STOCK_QUANTITY` INT NULL,
  PRIMARY KEY (`ITEM_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderItem` (
  `ORDER_ITEM_ID` INT NOT NULL,
  `COUNT` INT NULL,
  `ORDER_PRICE` INT NULL,
  `ORDER_ID` INT NULL,
  `ITEM_ID` INT NULL,
  PRIMARY KEY (`ORDER_ITEM_ID`),
  INDEX `ORDER_ID_idx` (`ORDER_ID` ASC) VISIBLE,
  INDEX `ITEM_ID_idx` (`ITEM_ID` ASC) VISIBLE,
  CONSTRAINT `ORDER_ID`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `mydb`.`Orders` (`ORDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ITEM_ID`
    FOREIGN KEY (`ITEM_ID`)
    REFERENCES `mydb`.`ITEM` (`ITEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `CATEGORY_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`CATEGORY_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITEM_has_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ITEM_has_Category` (
  `ITEM_ITEM_ID` INT NOT NULL,
  `Category_CATEGORY_ID` INT NOT NULL,
  PRIMARY KEY (`ITEM_ITEM_ID`, `Category_CATEGORY_ID`),
  INDEX `fk_ITEM_has_Category_Category1_idx` (`Category_CATEGORY_ID` ASC) VISIBLE,
  INDEX `fk_ITEM_has_Category_ITEM1_idx` (`ITEM_ITEM_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ITEM_has_Category_ITEM1`
    FOREIGN KEY (`ITEM_ITEM_ID`)
    REFERENCES `mydb`.`ITEM` (`ITEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEM_has_Category_Category1`
    FOREIGN KEY (`Category_CATEGORY_ID`)
    REFERENCES `mydb`.`Category` (`CATEGORY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
